### ISSUE TITLE
Live View Broken

### ISSUE THREAD

**Issue by LeoWoerteler** [JosuaKrause/BusVis#57]
The _now_ view can't be chosen any more, it runs into an infinite loop:

```
at infovis.ctrl.Controller.setTime(Controller.java:282)
at infovis.ctrl.Controller.setFastForwardMode(Controller.java:467)
at infovis.ctrl.Controller.setTime(Controller.java:282)
at infovis.ctrl.Controller.setFastForwardMode(Controller.java:467)
at infovis.ctrl.Controller.setTime(Controller.java:282)
at infovis.ctrl.Controller.setFastForwardMode(Controller.java:467)
```

Seems to to introduced by #52.

**Comment by LeoWoerteler** [comment]
Should be fixed before merging #56.
